//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityLocalize
{
    
    
    public partial class InlineStrings
    {
        
        private static UnityLocalize.LocalizableString _AkiasONE = new UnityLocalize.LocalizableString("AkiasONE", new string[] {
                    "12sdfsfgs",
                    "fsdfsdfsd"});
        
        /// <summary>
        /// 12sdfsfgs
        /// </summary>
        public static UnityLocalize.LocalizableString AkiasONE
        {
            get
            {
                return UnityLocalize.InlineStrings._AkiasONE;
            }
        }
    }
}
